stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/interim
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/interim
    - src/feature_engineering.py
    outs:
    - data/processed
  model_building:
    cmd: python src/model_training.py
    deps:
    - data/processed
    - src/model_training.py
    outs:
    - models/random_forest_model.pkl
  model_evaluation:
    cmd: python src/model_evalaution.py
    deps:
    - models/random_forest_model.pkl
    - src/model_evalaution.py
    metrics:
    - reports/metrics.json